language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          packages:
            - cmake
            - graphviz
            - doxygen
            - nvidia-cuda-toolkit
   - os: linux
     dist: bionic
     compiler: gcc
     addons:
       apt:
         packages:
           - cmake
           - graphviz
           - doxygen
           - nvidia-cuda-toolkit
           - libgl1-mesa-dev
           - libglfw3
           - libglfw3-dev

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version

branches:
  only:
    - master

script: ./build.sh /tmp/build
